export const LOGIN_API = '/auth/login'
export const REGISTER_API = '/auth/signup'
export const CHANGE_PASSWORD = '/auth/change_password'
export const REFREST_TOKEN = '/auth/refresh'
export const LOGOUT_API = '/auth/logout'
